const About = () => {
    return (
      <div className="container mt-5 pb">
      <h1 className="display-4 text-center mb-5">About Our Project</h1>
  
      <div className="card mb-4">
          <div className="card-body">
              <h2 >Project Overview</h2>
              <p>
                  Our project is a pioneering initiative focused on the
                  development of an advanced machine learning model designed
                  to automate the identification and comprehensive analysis of
                  plant leaf health. The primary goal is to address the
                  critical challenge of early detection of plant diseases,
                  aiming to significantly impact global crop yield and enhance
                  food production sustainability.
              </p>
          </div>
      </div>
  
      <div className="card mb-4">
          <div className="card-body">
              <h2 >Empowering Farmers</h2>
              <p>
                  This transformative project serves as a beacon for farmers,
                  providing them with a cutting-edge application that
                  revolutionizes disease identification processes. Our
                  intuitive platform invites farmers to upload photographs of
                  disease-affected plants, unleashing the power of a
                  sophisticated deep learning model infused with Explainable
                  AI (XAI). The model not only predicts diseases with
                  unparalleled accuracy but also offers detailed explanations,
                  demystifying the decision-making process for users.
              </p>
          </div>
      </div>
  
      <div className="card mb-4">
          <div className="card-body">
              <h2 >Seamless Collaboration</h2>
              <p>
                  Moreover, the predictive insights generated by the
                  application can be seamlessly transmitted to experts and
                  scientists for a comprehensive review, approval, and
                  additional recommendations if deemed necessary. The
                  underlying technology relies on the fusion of deep learning
                  and Explainable AI, reinforcing the accuracy and reliability
                  of solutions delivered through this dynamic web-based
                  application.
              </p>
          </div>
      </div>
  
      <div className="card">
          <div className="card-body">
              <h2 >Join Us in Transforming Agriculture</h2>
              <p>
                  We invite you to join us in this transformative journey to
                  empower farmers and contribute to the sustainability of
                  global food production. Together, we can make a significant
                  impact on agriculture using the latest advancements in
                  technology.
              </p>
          </div>
      </div>
  </div>
    );
};

export default About;
